{% set name = "xrootd" %}
{% set version = "5.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xrootd/xrootd/archive/v{{ version }}.tar.gz
  sha256: c604e32ad259e4e5a24df2e298a35e65a82599b75402a8b505c827c24e4c9a0d

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/xrootd/
    - {{ pin_subpackage('xrootd', max_pin='x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
    - pip                                    # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - cmake
    - make
    - pkg-config
  host:
    - openssl
    - python
    - setuptools
    - pip
    - readline
    - libxml2
    - libuuid  # [not osx]
    - libcurl
    - krb5
    - zlib
    - ncurses
    - scitokens-cpp
  run:
    - openssl
    - python
    - readline
    - libxml2
    - krb5
    - zlib
    - ncurses

test:
  imports:
    - XRootD.client
    - pyxrootd

about:
  home: http://xrootd.org/
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: High performance, scalable fault tolerant access to data

  description: |
    The XROOTD project aims at giving high performance, scalable fault tolerant
    access to data repositories of many kinds. The typical usage is to give
    access to file-based ones. It is based on a scalable architecture, a
    communication protocol, and a set of plugins and tools based on those. The
    freedom to configure it and to make it scale (for size and performance)
    allows the deployment of data access clusters of virtually any size, which
    can include sophisticated features, like authentication/authorization,
    integrations with other systems, WAN data distribution, etc.
  dev_url: https://github.com/xrootd/xrootd

extra:
  recipe-maintainers:
    - chrisburr
