schema_version: 1

context:
  name: xrootd
  version: "5.9.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/xrootd/xrootd/archive/v${{ version }}.tar.gz
  sha256: d26d77a676674f52cdb5997b71eb6414d68e8e3067ce7a2201dc4d660b29e498

build:
  number: 1
  skip: win

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - setuptools
        - pip
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
  host:
    - openssl
    - python
    - setuptools
    - pip
    - readline
    - libxml2-devel
    - if: not osx
      then: libuuid
    - libcurl
    - krb5
    - zlib
    - ncurses
    - scitokens-cpp
    - libxcrypt
  run:
    - openssl
    - python
    - readline
    - libxml2-devel
    - krb5
    - zlib
    - ncurses
  run_exports:
    - ${{ pin_subpackage('xrootd', upper_bound='x') }}

tests:
  - python:
      imports:
        - XRootD.client
        - pyxrootd

about:
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: High performance, scalable fault tolerant access to data
  description: |
    The XROOTD project aims at giving high performance, scalable fault tolerant
    access to data repositories of many kinds. The typical usage is to give
    access to file-based ones. It is based on a scalable architecture, a
    communication protocol, and a set of plugins and tools based on those. The
    freedom to configure it and to make it scale (for size and performance)
    allows the deployment of data access clusters of virtually any size, which
    can include sophisticated features, like authentication/authorization,
    integrations with other systems, WAN data distribution, etc.
  homepage: http://xrootd.org/
  repository: https://github.com/xrootd/xrootd

extra:
  recipe-maintainers:
    - chrisburr
